### ISSUE TITLE
Allow setting file permissions

### ISSUE THREAD

**Issue by krisavi** [puppetlabs/puppetlabs-yumrepo_core#74]
For some reason the target permissions are fixed to 0644
https://github.com/puppetlabs/puppetlabs-yumrepo_core/blob/26619723926e101332ffe29a9cc3b619e2474859/lib/puppet/provider/yumrepo/inifile.rb#L247

Could it be changed using parameter when generating file?

Currently in our case we set permisisons to 0600 using File resource, then yumrepo comes and changes it to 0644 and again File resource goes over doing corrective actions. 

Another alternative would be to allow using Yumrepo resource target => File['file_name'] syntax to manage permissions and ownership in File resource, but Yumrepo for the content of the file without going for template route.

**Comment by cthorn42** [comment]
Thanks for filing this issue @krisavi, after going over this issue with our team we agree this could be considered a valid case. However we don't have the bandwidth to work on this in the future so we're goin to close this issue out.
